# devices.py

SOLAR_ENGINES = {
    "se_mini": {
        "key": "se_mini",
        "name": "Solar Engine Mini",
        "short_name": "SE MINI",
        "pv": 40,
        "batt": 336,
        "batt_ext": None,
        "tilt_options": [33],
        "fixed": True,
    },
    "se_compact": {
        "key": "se_compact",
        "name": "Solar Engine Compact",
        "short_name": "SE COMPACT",
        "pv": 185,
        "batt": 1440,
        "batt_ext": 2880,
        "tilt_options": [15, 35, 55],
        "fixed": False,
    },
    "se_max": {
        "key": "se_max",
        "name": "Solar Engine Max",
        "short_name": "SE MAX",
        "pv": 720,
        "batt": 3000,
        "batt_ext": 6000,
        "tilt_options": [15, 35, 55],
        "fixed": False,
    },
}

DEVICES = {
    1: {
        "code": "SP-401SMI",
        "name": "PRO SP-401SMI",
        "system_type": "builtin",
        "default_power": 2.6,
        "pv": 25,
        "batt": 216,
        "tilt": 33,
        "fixed": True,
    },
    2: {
        "code": "SP-501SHI",
        "name": "CAT-I SP-501SHI",
        "system_type": "builtin",
        "default_power": 8.0,
        "pv": 25,
        "batt": 216,
        "tilt": 33,
        "fixed": True,
    },
    3: {
        "code": "SP-301SLI",
        "name": "STD SP-301SLI",
        "system_type": "builtin",
        "default_power": 1.4,
        "pv": 5,
        "batt": 54,
        "tilt": 33,
        "fixed": True,
    },
    4: {
        "code": "SP-200",
        "name": "SP-200 Inset Light",
        "system_type": "external_engine",
        "default_power": 5.0,
        "default_engine": "se_mini",
        "compatible_engines": ["se_mini", "se_compact", "se_max"],
    },
    5: {
        "code": "PAPI",
        "name": "PAPI",
        "system_type": "external_engine",
        "default_power": 320.0,
        "default_engine": "se_max",
        "compatible_engines": ["se_mini", "se_compact", "se_max"],
    },
    6: {
        "code": "A-PAPI",
        "name": "A-PAPI",
        "system_type": "external_engine",
        "default_power": 160.0,
        "default_engine": "se_max",
        "compatible_engines": ["se_mini", "se_compact", "se_max"],
    },
    7: {
        "code": "RGL",
        "name": "Runway Guard Light",
        "system_type": "external_engine",
        "default_power": 3.0,
        "default_engine": "se_mini",
        "compatible_engines": ["se_mini", "se_compact", "se_max"],
    },
    8: {
        "code": "WDI",
        "name": "Wind Direction Indicator",
        "system_type": "external_engine",
        "default_power": 10.0,
        "default_engine": "se_mini",
        "compatible_engines": ["se_mini", "se_compact", "se_max"],
    },
    9: {
        "code": "SIGN-L",
        "name": "Large Guidance Sign",
        "system_type": "external_engine",
        "default_power": 35.0,
        "default_engine": "se_compact",
        "compatible_engines": ["se_mini", "se_compact", "se_max"],
    },
    10: {
        "code": "SIGN-M",
        "name": "Medium Guidance Sign",
        "system_type": "external_engine",
        "default_power": 22.0,
        "default_engine": "se_compact",
        "compatible_engines": ["se_mini", "se_compact", "se_max"],
    },
    11: {
        "code": "SIGN-S",
        "name": "Small Guidance Sign",
        "system_type": "external_engine",
        "default_power": 15.0,
        "default_engine": "se_compact",
        "compatible_engines": ["se_mini", "se_compact", "se_max"],
    },
}
